### ISSUE TITLE
Implement mirror-node command

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#116]
Currently mirror-node is setup during `node start`. We should separate it out in a separate command so that we have more control:

- `solo mirror-node start`
- `solo mirror-node stop`

`node start` does not need to deploy `mirror-node` anymore which would reduce delays on various account related tasks/tests.

**Comment by leninmehedy** [comment]
@JeffreyDallas Any thoughts on this?

**Comment by jeromy-cannon** [comment]
makes sense.  `solo mirror-node start` is easy, we already have the code for that.  for `solo mirror-node stop` would you do a `helm upgrade` with it disabled?  it would leave behind the postgres pvc unless that is removed manually.  If we are removing the components, I'm not sure that `stop` is a good command.

we could go with `solo mirror-node deploy` and `solo mirror-node destroy`

**Comment by leninmehedy** [comment]
> we could go with `solo mirror-node deploy` and `solo mirror-node destroy`

That sounds good. Let's go with deploy/destroy.

**Comment by leninmehedy** [comment]
@jeromy-cannon I'm assigning this to you since you have been working on mirror-node stuff and have more clarity on how to do it.
