### ISSUE TITLE
Convert current CLI user docs to a Hugo theme based docs site

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#118]
We would like to use Hugo for our docs site, see demo: https://geekdocs.de/
Here is the Hugo theme template: https://themes.gohugo.io/themes/hugo-geekdoc/

This task involves converting the user documentation in README.md to a docs site. README needs to be updated with the link to the docs site.

For example, the site URL may look like: https://hashgraph.github.io/solo

**Comment by JeffreyDallas** [comment]
Done with PR #200
