### ISSUE TITLE
HAProxy UP check is unreliable

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#169]
Currently HAProxy status is checked using the log. However, it often fails to log the message because probably it gives up retrying....Also if HAProxy is restarted, it looses the logs and does not output the line `Server be_servers/server1 is UP` consistently (See https://github.com/hashgraph/solo/blob/c6474de87a2f1a14fd393a9cbe614f606ebbf3fc/src/commands/node.mjs#L557). 

As a result, `solo` fails to report if node start was successful.

My initial solution was to restart HAProxy, however even after manually restarting, it didn't solve the issue as HAProxy didn't output the log message `Server be_servers/server1 is UP` although sdk was able to invoke transactions. When I viewed `/stats`, it did report that node was up.

We need to figure out a reliable way to check if HAProxy is UP or not. Not sure if we can use the HAProxy `/stats` endpoint?, or use hedera-sdk to poll? 

Notes:
- If you would like to view the `/stats` endpoint, it is a bit complicated as below
  - Expose port 9090 of the HAProxy service (e.g. `haproxy-node0-svc`)
  - Open the corresponding configmap and at the bottom you will find the `auth` block separated by `:`. First part is username and the second part is the password.
  - Go to `localhost:9090/stats` and when prompted enter the username and password.

**Comment by jeromy-cannon** [comment]
talking with Nathan, we can run the data plane api which will give us the endpoints to check for the status.  

https://www.haproxy.com/documentation/haproxy-data-plane-api/installation/install-on-haproxy/
