### ISSUE TITLE
Duplicate PR steps are confusing

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#253]
There are two PR steps for unit tests and two for E2E tests. The name should include the OS to distinguish them. Currently it looks confusing as to why there are duplicates. Also the PR check for windows seem to skip steps

<img width="775" alt="Screenshot 2024-04-27 at 8 27 04 PM" src="https://github.com/hashgraph/solo/assets/811437/e49a04ed-5fac-4832-bcf5-4f9b6116171c">

This is not urgent, but nice to have.

**Comment by JeffreyDallas** [comment]
already implemented in workflow
