### ISSUE TITLE
Bug: Unit tests suite fails if ran without having a Kubernetes cluster running locally (kube config exists)

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#359]
The Unit Tests that fail when running without a Kubernetes cluster when running locally should be updated to load a mock of K8 to avoid the failures generated when K8 finds a kube context.

**Comment by instamenta** [comment]
I personally don't have any problem with running the tests, even without running docker

**Comment by jeromy-cannon** [comment]
Must be the way my machine is setup.  renaming the ~/.kube/config seemed to make the problem go away as we saw on the call the other day.

**Comment by jeromy-cannon** [comment]
If you can't reproduce it, then maybe I can work it later, or if @JeffreyDallas can reproduce it on his machine.
