### ISSUE TITLE
Add a means to configure Solo's mirror node version

### ISSUE THREAD

**Issue by edwin-greene** [hashgraph/solo#495]
### Feature to Enhance

The configurability of the version of the mirror node that Solo deploys.

### Requested Enhancement

Add a means of configuring the version of the Mirror Node that Solo deploys. The version deployed should be configurable to be used inside of a Github workflow (set to the version that is currently being built by the workflow triggered by the PR). Also it would be beneficial to be able to configure Solo to deploy to a specific released version (for example, 0.111.0 in one test and 0.110.0 in another).

### Business Need

To use Solo with Github workflows in a CI/CD pipeline, we would like to run Mirror Node acceptance tests with each build. The version of the mirror node that Solo deploys should be the version that has been built in the Github workflow. This will be needed to unblock Mirror Node issue [#8513: Test acceptance tests in CI](https://github.com/hashgraph/hedera-mirror-node/issues/8513).

**Comment by steven-sheehy** [comment]
Note this is possible by setting `--set global.image.tag=0.110.0` via Helm on our wrapper chart.
