### ISSUE TITLE
Hugo Deploy concurrency issue

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#668]
```[tasklist]
### Tasks
- [ ] update `flow-hugo-publish.yaml` so that `build` and `deploy` are capitalized to match the rest of the workflow jobs
- [ ] ensure `Deploy Hugo sites to Pages` does not pick up `Unit Test Results - Linux`, `Unit Test Results - Windows`.  and `E2E Test Report`, see screenshots and links below...
```

- https://github.com/hashgraph/solo/actions/runs/11255769974 
![image](https://github.com/user-attachments/assets/a10b0da1-92d7-4096-bb8c-f9d583a7424a)

- https://github.com/hashgraph/solo/actions/runs/11255712886
![image](https://github.com/user-attachments/assets/cbccb66b-919c-4a06-9f98-3f95202d2325)

**Comment by JeffreyDallas** [comment]
I dont' understand why Unit test steps showing up in the hugo work flow

https://github.com/hashgraph/solo/actions/runs/11273683958

But I checked artffact, no any unit test results were included.

**Comment by JeffreyDallas** [comment]
I manually kicked off huge page workflow,
it did not show any unit test steps at all

https://github.com/hashgraph/solo/actions/runs/11278658135

**Comment by jeromy-cannon** [comment]
I know, weird right!  I think it only happens when there are multiple PRs and/or `main` running at the same time.  it must be sharing something.
