### ISSUE TITLE
deployMirrorNode and deployHederaExplorer command argument does not work

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#69]
When I run `network deploy --mirror-node --hedera-explorere` it doesn't use these arg values as before:

<img width="1152" alt="Screenshot 2024-02-26 at 11 56 53 AM" src="https://github.com/hashgraph/solo/assets/811437/b70ede10-6dfc-4d8e-87d8-234721fd4b86">

**Comment by leninmehedy** [comment]
Just realized those are disabled because it is deployed during `node start` command.

We should remove those from `network deploy` command.

**Comment by jeromy-cannon** [comment]
I believe this is no longer valid, closing
