### ISSUE TITLE
an error was encountered while trying to prepare the address book

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#70]
Error happened when I ran `solo node start`. We need to provide some instructions to the user on how it can be resolved. 

We probably need to allow user to retry the mirror-node deployment part only.

<img width="577" alt="Screenshot 2024-02-26 at 12 49 02 PM" src="https://github.com/hashgraph/solo/assets/811437/b2993820-68bc-4610-9cdd-aaa156c7c799">

**Comment by jeromy-cannon** [comment]
I don't think this is a valid issue any more.  closing.
