### ISSUE TITLE
System accounts are not imported in Mirror node

### ISSUE THREAD

**Issue by Ivo-Yankov** [hashgraph/solo#766]
### To Reproduce

Create a new local deployment with a single network node and a mirror node:

```markdown
export SOLO_CLUSTER_NAME=solo
export SOLO_NAMESPACE=solo
export SOLO_CLUSTER_SETUP_NAMESPACE=solo-cluster
kind create cluster -n "${SOLO_CLUSTER_NAME}"
npm run solo -- init
npm run solo -- node keys --gossip-keys --tls-keys -i node1
npm run solo -- cluster setup -s "${SOLO_CLUSTER_SETUP_NAMESPACE}"
npm run solo -- network deploy -i node1 -n "${SOLO_NAMESPACE}"
npm run solo -- node setup -i node1 -n "${SOLO_NAMESPACE}"
npm run solo -- node start -i node1 -n "${SOLO_NAMESPACE}"
npm run solo -- mirror-node deploy -n "${SOLO_NAMESPACE}"
```

Forward the mirror node rest api port:
```
kubectl port-forward -n ${SOLO_NAMESPACE} $(cut -d' ' -f1 <<<$(kubectl get pods -n ${SOLO_NAMESPACE} | grep solo-deployment-rest-)) 5551 &
```

Observe that there is no data in `http://localhost:5551/api/v1/accounts`

### Describe the bug

The data for the system accounts is not imported to the mirror node.

**Comment by jeromy-cannon** [comment]
@Ivo-Yankov , when you genesis, then the first record stream file is in an open state, you need transactions to get the record stream to close and get published to Mirror Node.  Synthetic records will not close the stream.  Until you have a user transaction or transactions coming from the monitor, then the record stream won't close and Mirror Node won't get updated.

**Comment by JeffreyDallas** [comment]
I tested with Ivo's steps then followed some account creation test, 
also tried the mirror node end-to-end test, in both cases, newly accounts showed up in explorer.

So I wonder if system account ever should be shown in explorer.


<img width="1604" alt="Screenshot 2024-11-05 at 12 14 15 PM" src="https://github.com/user-attachments/assets/f996ba0c-9160-4cde-900f-f31d2660691b">
<img width="1602" alt="Screenshot 2024-11-05 at 12 46 41 PM" src="https://github.com/user-attachments/assets/96975adb-8bef-430e-bbc1-74802afb5535">

**Comment by JeffreyDallas** [comment]
I confirmed with Xin from mirror node team, only system files generated through transactions (so has related 
record stream file) would be shown up in explorer.

**Comment by jeromy-cannon** [comment]
@JeffreyDallas , so system accounts would never show up in Mirror?

**Comment by JeffreyDallas** [comment]
> @JeffreyDallas , so system accounts would never show up in Mirror?

Only if they were existed in record stream files.

**Comment by JeffreyDallas** [comment]
Confirmed.

![Image](https://github.com/user-attachments/assets/15c586b2-1b5a-4f9f-96de-ca754185a861)
