### ISSUE TITLE
Resolve issues with Node Delete E2E tests

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/solo#864]
### Describe the bug

The Delete Node end to end tests are currently failing due to the changes introduced in #856. 

### Describe the expected behavior

The Delete Node end to end tests should pass.

### To Reproduce

1. Run any of the Delete Node end to end tests locally or in CI.

**Comment by jeromy-cannon** [comment]
closed by https://github.com/hashgraph/solo/pull/866
