### ISSUE TITLE
Network node alias -1 bug

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#878]
Issue in latest main:
Seems enumeration logic of hedera-nodes shifted from 0-($SOLO_NETWORK_SIZE-1) to 1-($SOLO_NETWORK_SIZE) that causes hanging waiting for non-existing last node:
Clue:
```
[helper:solo:network:deploy] 
task: [helper:solo:network:deploy] solo network deploy --namespace "${SOLO_NAMESPACE}" --node-aliases-unparsed node1,node2,node3,node4,node5,node6,node7
```
working sequence before was : node0, ..., node6
Infinite wait for node7:
```
{"label":"","level":"DEBUG","message":"[attempt: 272/900] 0/1 pod found [labelSelector: solo.hedera.com/node-name=node7,solo.hedera.com/type=network-node, namespace:solo-hashsphere1]","ms":"+1s","timestamp":"2024-11-25T20:13:44.738Z","traceId":"e8360281-9cdf-46da-8d4c-1d3d8e8fd85c"}
while nodes network-node0-0 to network-node6-0 already OK deployed
```

**Comment by JeffreyDallas** [comment]
Did not we already resolved this ? all using node1, node2, etc

**Comment by jeromy-cannon** [comment]
@JeffreyDallas , sorry, I added the description, but must have forgot to hit save.  this is different, and something we introduced recently.
