### ISSUE TITLE
Cannot set custom resources for *uploader containers

### ISSUE THREAD

**Issue by alex-kuzmin-hg** [hashgraph/solo#926]
### Describe the bug

It is impossible to modify resource values for containers *-uploader
via external init-container-values.yml

We must have a mechanism of updating, because default values do not fit to HashSphere.

### Describe the expected behavior

To let user modify input value file

### To Reproduce

Currently, the values for *-uploaders ignored:
1) modify init-containers-values.yaml
2) call 
~/.solo/bin/helm template solo-deployment oci://ghcr.io/hashgraph/solo-charts/solo-deployment --version 0.34.0 -n solo-hashsphere2 --create-namespace --values ~/.solo/cache/values-files/solo-local.yaml --set \"telemetry.prometheus.svcMonitor.enabled=false\" --set \"defaults.root.image.repository=hashgraph/solo-containers/ubi8-init-java21\" --set \"defaults.volumeClaims.enabled=false\" --values ./init-containers-values.yaml
3) no resources taken

**Comment by alex-kuzmin-hg** [comment]
Jefferey has advised the solution that unblocked HashSphere testing.

Next steps, per Nathan:

 "we could do better by exposing it in the helm chart as an explicit configuration which does not require overriding an entire container definition.
But as 
@alex.kuzmin
 pointed out it is a real solution (albiet an ugly one) which we can improve the helm chart and/or solo to make it cleaner and easier."

**Comment by JeffreyDallas** [comment]
@alex-kuzmin-hg 
I am closing the ticket since I verified that we should be able to set resources for each indvidual containers

```xml
  nodes:
    - name: node1
      accountId: 0.0.3
      sidecars:
        recordStreamSidecarUploader:
          enabled: true
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              cpu: 3m
              memory: 4Mi
    - name: node2
      accountId: 0.0.4
      sidecars:
        recordStreamSidecarUploader:
          enabled: true
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              cpu: 3m
              memory: 4Mi
```

The key is to add `enabled: true` to each individual uploader, otherwise it will not be instantiated.
