### ISSUE TITLE
swirlds.log shouldn’t be in DEBUG mode

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#95]
Currently `/opt/hgcapp/sevices-hedera/HapiApp2.0/logs/swirlds.log` is in DEBUG mode and very noisy. We need to set it to be in INFO mode.

Need to figure out what settings is needed to set it to be INFO mode similar to our testnet/mainnet. 

Ref: 
1. https://github.com/hashgraph/solo/blob/main/resources/templates/bootstrap.properties#L2
2. https://github.com/hashgraph/solo/tree/main/resources/templates

**Comment by JeffreyDallas** [comment]
Is this issue still unresolved ?

I checked swirds.log in solo node, and compared with what default logs results from nightly regression,
not seeing any extra log. log4j2.xml configuration is also very similar/match default settings in regrssion tests.

If this still is an issue, please post some log examples shownig it has extra unnecssary noise in it.

**Comment by leninmehedy** [comment]
@JeffreyDallas We need to replace `level="TRACE"` with `level="INFO"` in the log4j2.xml file
- https://github.com/hashgraph/solo/blob/main/resources/templates/log4j2.xml#L56
- https://github.com/hashgraph/solo/blob/main/resources/templates/log4j2.xml#L61
