### ISSUE TITLE
Cannot install new version: missing key "app.kubernetes.io/managed-by"

### ISSUE THREAD

**Issue by alex-kuzmin-hg** [hashgraph/solo#966]
### Describe the bug

At step "helper:solo:network:deploy", it fails:
[helper:solo:network:deploy] ✖ Check if cluster setup chart is installed [FAILED: Chart solo-cluster-setup is not installed. Run 'solo cluster setup']
task: Failed to run task "default": exit status 1

direct call shows potential culprit:
```
/home/cluster5/.solo/bin/helm install solo-cluster-setup oci://ghcr.io/hashgraph/solo-charts/solo-cluster-setup --version 0.35.0 -n solo-setup --create-namespace  --set cloud.prometheusStack.enabled=false --set cloud.minio.enabled=true --set cloud.certManager.enabled=false --set cert-manager.installCRDs=false
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/lib/teleport/credentials/k8s-pft-dal/kubeconfig.yaml
Pulled: ghcr.io/hashgraph/solo-charts/solo-cluster-setup:0.35.0
Digest: sha256:822238f9010784c9c5b579a968e95bf89afc10524e4073506366355e5ac3cab9
Error: INSTALLATION FAILED: Unable to continue with install: CustomResourceDefinition "tenants.minio.min.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "solo-cluster-setup"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "solo-setup"
```

### Describe the expected behavior

must run 'task -t Taskfile.yml' fine

### To Reproduce

task -t Taskfile.yml 
on Latitude

**Comment by alex-kuzmin-hg** [comment]
NAthan:
"Check if cluster setup chart is installed [FAILED: Chart solo-cluster-setup is not installed. Run 'solo cluster setup']
This is the real failure, we should not require the solo-cluster-setup chart to be installed 
Preprovisioned clusters with all the necessary dependencies like the latitude cluster will not have the solo-cluster-setup chart
"

**Comment by jeromy-cannon** [comment]
```
CustomResourceDefinition "tenants.minio.min.io" in namespace "" exists and cannot be imported into the current release
```

This means that you minio already exists, try adding the `--no-minio` to the `solo cluster setup` flags.
