### ISSUE TITLE
Allow solo to deploy pre-configured network to support desired workload

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#97]
### Requested Feature

```markdown
`solo` could have switches to deploy networks with pre-configured resources to support various TPS.

For example, we could support :
 - `large` (<= 10K TPS), 
 - `medium` (<= 5K TPS)
 - `small` (<= 1K TPS)

Currently starting a network requires running a sequence of commands. While that is beneficial to have more control, `solo` could also provide a simpler command like `start` and `stop` as below:
`solo start --profile large`
`solo start --profile medium`
`solo start --profile small`
```

### Business Need

```markdown
Make it easier for user to deploy a network that meets their need.

Currently it requires users to try different settings to see which configuration achieves the desired TPS. We could do the heavy lifting of determining the resources required for various desired network load and let user deploy it confidently.

We also need to tell the cluster configuration that is required for `solo` to be able to deploy a network to achieve the desired workload.
```

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo/issues/85
```

**Comment by JeffreyDallas** [comment]
Agree this, so from DApp developers' perspective, they don't need to care about
 how solo works and what is under the hood.
It is better that they don't even aware of cluster being used. (Solo does everything behind the door)

**Comment by jeromy-cannon** [comment]
great idea.  Would they be able to pass more parameters/options, or would they be locked into whatever the profile is configured at?

For example, it might run faster without Hedera Mirror Node/Explorer

**Comment by leninmehedy** [comment]
I asked Richard, and he suggested we go with the below for now:
1. Large = 48 vCPU 256GB RAM
2. Medium = 36 vCPU 128GB RAM
3. Small = 12vCPU 32GB RAM
4. Tiny = 4vCPU 8GB RAM

**Comment by leninmehedy** [comment]
I prepared a rough estimate and definition of these pre-configured profiles here: https://www.notion.so/swirldslabs/Pre-configured-Profiles-DRAFT-8c843489a92048eabf4b68db46a9ba46?pvs=4
